version: '3.8'

services:
  app:
    image: jakgwi/dockerlabmasterdemo0320:0.0.1
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/labmaster?autoReconnect=true&allowPublicKeyRetrieval=true&true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
    depends_on:
      - db

  db:
    image: mysql:8.0.27
    environment:
      DATABASE_HOST: docker-mysql
      DATABASE_PORT: 3306
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: labmaster
      MYSQL_USER: root
      MYSQL_PASSWORD: