spring:
  datasource:
    url: jdbc:mysql://localhost:3306/labmaster?autoReconnect=true&allowPublicKeyRetrieval=true&true&useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
jpa:
  database-platform: org.hibernate.dialect.MySQL5Dialect
  hibernate:
    ddl-auto: update